### PR TITLE
Exit immediately when the user hits Escape

### PR DESCRIPTION
**Pull request by herbygillot**
One more PR - posting here as I'm not yet set up on Sourcehut.

### CODE REVIEW

**Comment by gpanders** [comment]
Thanks!

PRs here are fine, but just as an FYI you don't need an account on Sourcehut, you can simply send your patch to <~gpanders/ijq-devel@lists.sr.ht> with `git send-email`.

**Comment by gpanders** [comment]
Merged!

**Comment by gpanders** [comment]
Btw I just cut a new release (0.3.0) with the two new features you implemented.

**Comment by herbygillot** [comment]
OK great, thank you

**Comment by herbygillot** [comment]
Alright, port updated: https://github.com/macports/macports-ports/commit/3dcc3e36194dc6aedfd3483841a024ead47c87d1

**Pull request closed without merging**
