### PR TITLE
Fix history

### PR DESCRIPTION
**Pull request by herbygillot**
Recent changes in 0.3.2 broke history.  These commits resolve the issue.

### CODE REVIEW

**Comment by herbygillot** [comment]
I think we're at the point where we need to break functions out and have tests.

**Comment by gpanders** [comment]
Hm, weird, I tested it and it worked, maybe there was some edge case or something.

> I think we're at the point where we need to break functions out and have tests.

Yes I have thought that for a long time, but that is the less fun part so I've been procrastinating :)

**Comment by gpanders** [comment]
I'd like to understand why this broke, can you give me some more details? How big is your history file, and when you say it broke, what happened exactly? It seems to be working just fine for me so I'm not sure why it's not working for you.

**Comment by herbygillot** [comment]
You can see the details in the commit messages for each commit in this PR.

But basically:

Case 1: bad permissions. Looks like you saw that while I was typing this.

Case 2: Filter expressions are getting split on all whitespace, so a single expression gets split into every token in the autocomplete menu.

**Comment by gpanders** [comment]
> Case 2: Filter expressions are getting split on all whitespace, so a single expression gets split into every token in the autocomplete menu.

Yep, makes sense. Good catch, and I should have thought of that. Thanks for finding both of these and fixing them.

**Comment by herbygillot** [comment]
Np.

> Yes I have thought that for a long time, but that is the less fun part so I've been procrastinating :)

I can put a PR up with some tests at some point.

**Comment by herbygillot** [comment]
OK thanks for merging. I'll update the port.

**Pull request merged**
